# Generated by Django 5.2.4 on 2026-03-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("officeapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workreport",
            name="report_no",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="workreport",
            name="sl_no",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="workreport",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="workreport",
            name="labour_type",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="workreport",
            name="nos",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="workreport",
            name="remarks",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="workreport",
            name="site",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
