# Generated by Django 5.2.4 on 2026-03-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("officeapp", "0002_workreport_report_no_workreport_sl_no_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfficeExpense",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_no", models.IntegerField()),
                ("date", models.DateField(auto_now_add=True)),
                ("sl_no", models.IntegerField()),
                ("item", models.CharField(max_length=200)),
                ("department", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("remark", models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name="ExpenseReport",
        ),
    ]
