# Generated by Django 5.2.4 on 2026-03-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("officeapp", "0003_officeexpense_delete_expensereport"),
    ]

    operations = [
        migrations.AddField(
            model_name="officeexpense",
            name="paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
